/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/hello': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Hello Get
     * @description Return a simple hello message with version info.
     */
    get: operations['hello_api_hello_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    /**
     * Hello Head
     * @description Return a simple hello message with version info.
     */
    head: operations['hello_api_hello_head'];
    patch?: never;
    trace?: never;
  };
  '/api/app-config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Current Config
     * @description Get current application configuration.
     *
     *     Returns:
     *         Current configuration
     */
    get: operations['get_current_config_api_app_config_get'];
    /**
     * Update Config
     * @description Update application configuration with validation and data migration.
     *
     *     Args:
     *         config: New configuration
     *
     *     Returns:
     *         Updated configuration
     *
     *     Raises:
     *         HTTPException: If config save fails or data_dir change is invalid
     */
    put: operations['update_config_api_app_config_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/app-config/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset Config
     * @description Reset configuration to defaults, preserving data_dir if environments exist.
     *
     *     Returns:
     *         Reset configuration
     */
    post: operations['reset_config_api_app_config_reset_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/has-environments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Has Environments
     * @description Check if any environments have been created.
     *
     *     Returns:
     *         Dictionary with has_environments boolean
     */
    get: operations['get_has_environments_api_environments_has_environments_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Environments
     * @description List all environments.
     *
     *     Returns:
     *         List of environment configurations
     */
    get: operations['list_environments_api_environments_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/hardware': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Hardware Info
     * @description Get detected hardware information.
     *
     *     Returns:
     *         Hardware detection results
     */
    get: operations['get_hardware_info_api_environments_hardware_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/extras': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Available Extras
     * @description Get available extras for a repository version.
     *
     *     Note: Repository is guaranteed to exist since it's downloaded in step 2 (version selection).
     *
     *     Args:
     *         repo_id: Repository identifier
     *         ref: Git reference
     *         lang: Language code for localization
     *
     *     Returns:
     *         List of enriched extra information
     */
    get: operations['get_available_extras_api_environments_extras_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/generate-steps': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Installation Steps
     * @description Generate installation steps preview based on configuration.
     *
     *     Args:
     *         request: Environment configuration
     *         lang: Language code for localization
     *
     *     Returns:
     *         Generated installation steps
     */
    post: operations['generate_installation_steps_api_environments_generate_steps_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Environment
     * @description Start environment creation/installation.
     *
     *     Args:
     *         request: Environment configuration with optional custom steps
     *         lang: Language code for localization
     *
     *     Returns:
     *         Installation ID and status
     *
     *     Raises:
     *         HTTPException: If creation fails
     */
    post: operations['create_environment_api_environments_create_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/{env_id}/installation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Environment Installation Status
     * @description Get installation status for a specific environment.
     *
     *     Args:
     *         env_id: Environment identifier
     *
     *     Returns:
     *         Installation status for the environment
     *
     *     Raises:
     *         HTTPException: If no active installation found for the environment
     */
    get: operations['get_environment_installation_status_api_environments__env_id__installation_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/{env_id}/installation/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Environment Installation
     * @description Cancel the active installation for a specific environment.
     *
     *     Args:
     *         env_id: Environment identifier
     *
     *     Returns:
     *         Cancellation status
     *
     *     Raises:
     *         HTTPException: If no active installation found for the environment
     */
    post: operations['cancel_environment_installation_api_environments__env_id__installation_cancel_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/{env_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Environment Details
     * @description Get detailed information about a specific environment.
     *
     *     Args:
     *         env_id: Environment identifier
     *
     *     Returns:
     *         Environment configuration
     *
     *     Raises:
     *         HTTPException: If environment not found
     */
    get: operations['get_environment_details_api_environments__env_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Environment
     * @description Delete an environment.
     *
     *     Args:
     *         env_id: Environment identifier
     *
     *     Returns:
     *         Deletion status
     *
     *     Raises:
     *         HTTPException: If environment not found or deletion fails
     */
    delete: operations['delete_environment_api_environments__env_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/{env_id}/installation/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Installation
     * @description Start environment installation.
     *
     *     Creates a PTY session and returns the first command to execute.
     */
    post: operations['start_installation_api_environments__env_id__installation_start_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/{env_id}/installation/execute': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Execute Installation
     * @description Execute a command or report execution result.
     *
     *     If exit_code is None: execute the command
     *     If exit_code is provided: handle the result and get next command
     */
    post: operations['execute_installation_api_environments__env_id__installation_execute_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/environments/{env_id}/installation/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Installation Status
     * @description Get current installation status and steps.
     */
    get: operations['get_installation_status_api_environments__env_id__installation_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/repositories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Repositories
     * @description Get available repositories from configuration.
     *
     *     Returns:
     *         List of repository information
     */
    get: operations['get_repositories_api_repositories_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/repositories/{repo_id}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Repository Versions
     * @description Get available versions (tags/branches) for a repository.
     *
     *     Args:
     *         repo_id: Repository identifier
     *
     *     Returns:
     *         List of version information
     *
     *     Raises:
     *         HTTPException: If repository not found
     */
    get: operations['get_repository_versions_api_repositories__repo_id__versions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/repositories/{repo_id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Repository Status
     * @description Get the download status of a repository.
     *
     *     Returns:
     *         Dictionary with download status, last update time, cache path, and update availability
     */
    get: operations['get_repository_status_api_repositories__repo_id__status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/repositories/{repo_id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream Download Repository
     * @description Stream download progress for a repository.
     */
    get: operations['stream_download_repository_api_repositories__repo_id__download_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tools/git/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate Git Path
     * @description Validate a Git executable path.
     *
     *     Args:
     *         path_data: Dictionary containing "path" key
     *
     *     Returns:
     *         Validation result with version info
     */
    post: operations['validate_git_path_api_tools_git_validate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tools/git/which': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Git Path
     * @description Get the actual path to the git executable.
     *
     *     Returns:
     *         Dictionary with 'path' key containing the git executable path
     */
    get: operations['get_git_path_api_tools_git_which_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tools/git/bundled/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Bundled Git Status
     * @description Get the status of bundled (system) Git.
     *
     *     Returns:
     *         Dictionary with installation status, path, and version
     */
    get: operations['get_bundled_git_status_api_tools_git_bundled_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tools/git/bundled/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download Bundled Git
     * @description Download and install bundled Git.
     */
    get: operations['download_bundled_git_api_tools_git_bundled_download_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AdvancedConfig
     * @description Advanced configuration.
     */
    AdvancedConfig: {
      /**
       * Installation Timeout
       * @default 3600
       */
      installation_timeout: number;
      /**
       * Log Level
       * @default INFO
       * @enum {string}
       */
      log_level: 'INFO' | 'DEBUG' | 'TRACE';
      /**
       * Log Max Size Mb
       * @default 10
       */
      log_max_size_mb: number;
      /**
       * Log Backup Count
       * @default 5
       */
      log_backup_count: number;
    };
    /**
     * AppConfig
     * @description Application configuration.
     */
    'AppConfig-Input': {
      server?: components['schemas']['ServerConfig'];
      ui?: components['schemas']['UIConfig'];
      paths?: components['schemas']['PathsConfig'];
      tools?: components['schemas']['ToolsConfig'];
      repositories?: components['schemas']['RepositoriesConfig'];
      pypi?: components['schemas']['PyPIConfig'];
      huggingface?: components['schemas']['HuggingFaceConfig'];
      advanced?: components['schemas']['AdvancedConfig'];
    };
    /**
     * AppConfig
     * @description Application configuration.
     */
    'AppConfig-Output': {
      server?: components['schemas']['ServerConfig'];
      ui?: components['schemas']['UIConfig'];
      paths?: components['schemas']['PathsConfig'];
      tools?: components['schemas']['ToolsConfig'];
      repositories?: components['schemas']['RepositoriesConfig'];
      pypi?: components['schemas']['PyPIConfig'];
      huggingface?: components['schemas']['HuggingFaceConfig'];
      advanced?: components['schemas']['AdvancedConfig'];
    };
    /**
     * CancelInstallationResponse
     * @description Response for cancelling installation.
     */
    CancelInstallationResponse: {
      /** Success */
      success: boolean;
      /** Message */
      message: string;
    };
    /**
     * CreateEnvironmentRequest
     * @description Request to create an environment.
     */
    CreateEnvironmentRequest: {
      env_config: components['schemas']['EnvironmentConfig'];
      /** Custom Steps */
      custom_steps?: components['schemas']['EnvironmentInstallStep'][] | null;
    };
    /**
     * CreateEnvironmentResponse
     * @description Response for environment creation.
     */
    CreateEnvironmentResponse: {
      /** Installation Id */
      installation_id: string;
      /** Env Id */
      env_id: string;
      /** Status */
      status: string;
      /** Steps */
      steps: components['schemas']['EnvironmentInstallStep'][];
      /** Message */
      message: string;
    };
    /**
     * DeleteEnvironmentResponse
     * @description Response for deleting environment.
     */
    DeleteEnvironmentResponse: {
      /** Success */
      success: boolean;
      /** Message */
      message: string;
    };
    /**
     * EnvironmentConfig
     * @description Configuration for a specific LeRobot environment.
     */
    EnvironmentConfig: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Display Name */
      display_name: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
      /** Repo Id */
      repo_id: string;
      /** Repo Url */
      repo_url: string;
      /** Ref */
      ref: string;
      /** Commit Hash */
      commit_hash?: string | null;
      /** Python Version */
      python_version: string;
      /** Torch Version */
      torch_version: string;
      /** Torchvision Version */
      torchvision_version?: string | null;
      /** Torchaudio Version */
      torchaudio_version?: string | null;
      /** Cuda Version */
      cuda_version?: string | null;
      /** Rocm Version */
      rocm_version?: string | null;
      /** Extras */
      extras?: string[];
      /**
       * Status
       * @default pending
       * @enum {string}
       */
      status: 'pending' | 'installing' | 'ready' | 'error';
      /** Error Message */
      error_message?: string | null;
    };
    /**
     * EnvironmentInstallStep
     * @description Represents a single installation step.
     */
    EnvironmentInstallStep: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Comment */
      comment?: string | null;
      /** Commands */
      commands: string[];
      /** Cwd */
      cwd?: string | null;
      /** Env Vars */
      env_vars?: {
        [key: string]: string;
      };
      /**
       * Status
       * @default pending
       * @enum {string}
       */
      status: 'pending' | 'running' | 'success' | 'error';
      /** Logs */
      logs?: string[];
      /** Start Time */
      start_time?: string | null;
      /** End Time */
      end_time?: string | null;
      /** Exit Code */
      exit_code?: number | null;
    };
    /**
     * EnvironmentInstallationPlan
     * @description Complete installation plan with all required information.
     */
    EnvironmentInstallationPlan: {
      /** Env Dir */
      env_dir: string;
      /** Repo Dir */
      repo_dir: string;
      /** Venv Path */
      venv_path: string;
      /** Log File */
      log_file: string;
      /** Steps */
      steps: components['schemas']['EnvironmentInstallStep'][];
      /** Env Vars */
      env_vars?: {
        [key: string]: string;
      };
      /** Default Cwd */
      default_cwd: string;
    };
    /**
     * ExecuteInstallationResponse
     * @description Response for executing an installation step.
     */
    ExecuteInstallationResponse: {
      /** Status */
      status: string;
      /** Step Id */
      step_id?: string | null;
      /** Command Index */
      command_index?: number | null;
      /** Error */
      error?: string | null;
      next_step?: components['schemas']['NextStepInfo'] | null;
    };
    /**
     * ExecuteRequest
     * @description Request to execute a command.
     */
    ExecuteRequest: {
      /** Step Id */
      step_id: string;
      /** Command Index */
      command_index: number;
      /** Exit Code */
      exit_code?: number | null;
      /** Execution Id */
      execution_id?: string | null;
    };
    /**
     * ExtraInfo
     * @description Extra information for environment.
     */
    ExtraInfo: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /**
       * Category
       * @default other
       */
      category: string;
      /**
       * Category Label
       * @default
       */
      category_label: string;
      /**
       * Selected
       * @default false
       */
      selected: boolean;
    };
    /**
     * GenerateStepsRequest
     * @description Request to generate installation steps.
     */
    GenerateStepsRequest: {
      env_config: components['schemas']['EnvironmentConfig'];
    };
    /**
     * GenerateStepsResponse
     * @description Response for step generation.
     */
    GenerateStepsResponse: {
      /** Steps */
      steps: components['schemas']['EnvironmentInstallStep'][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HardwareInfo
     * @description Hardware detection information.
     */
    HardwareInfo: {
      /** Detected Cuda */
      detected_cuda: string | null;
      /** Detected Rocm */
      detected_rocm: string | null;
      /** Detected Driver */
      detected_driver: string | null;
      /** Detected Gpu */
      detected_gpu: string | null;
      /** Has Nvidia Gpu */
      has_nvidia_gpu: boolean;
      /** Has Amd Gpu */
      has_amd_gpu: boolean;
      /** Is Apple Silicon */
      is_apple_silicon: boolean;
    };
    /**
     * HasEnvironmentsResponse
     * @description Response for check_has_environments.
     */
    HasEnvironmentsResponse: {
      /** Has Environments */
      has_environments: boolean;
    };
    /**
     * HuggingFaceConfig
     * @description HuggingFace configuration.
     */
    HuggingFaceConfig: {
      /**
       * Token
       * @default
       */
      token: string;
      /**
       * Cache Dir
       * Format: path
       */
      cache_dir?: string;
    };
    /**
     * InstallationStatusResponse
     * @description Response for installation status.
     */
    InstallationStatusResponse: {
      /** Installation Id */
      installation_id: string;
      /** Env Id */
      env_id: string;
      /** Status */
      status: string;
      /** Progress */
      progress: number;
      /** Steps */
      steps: components['schemas']['EnvironmentInstallStep'][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Completed At */
      completed_at?: string | null;
    };
    /**
     * NextStepInfo
     * @description Information about the next step to execute.
     */
    NextStepInfo: {
      /** Step Id */
      step_id: string;
      /** Step Index */
      step_index: number;
      /** Total Steps */
      total_steps: number;
      /** Command Index */
      command_index: number;
      /** Command */
      command: string;
      /** Name */
      name: string;
    };
    /**
     * PathsConfig
     * @description Paths configuration.
     */
    PathsConfig: {
      /**
       * Data Dir
       * Format: path
       */
      data_dir?: string;
      /** Repos Dir */
      repos_dir?: string | null;
      /** Environments Dir */
      environments_dir?: string | null;
      /** Logs Dir */
      logs_dir?: string | null;
      /** Cache Dir */
      cache_dir?: string | null;
      /** Uv Cache Dir */
      uv_cache_dir?: string | null;
      /** Tools Cache Dir */
      tools_cache_dir?: string | null;
      /** Tools Dir */
      tools_dir?: string | null;
    };
    /**
     * PyPIConfig
     * @description PyPI configuration.
     */
    PyPIConfig: {
      /** Mirrors */
      mirrors?: components['schemas']['PyPIMirror'][];
    };
    /**
     * PyPIMirror
     * @description PyPI mirror configuration.
     */
    PyPIMirror: {
      /** Name */
      name: string;
      /** Url */
      url: string;
      /**
       * Enabled
       * @default false
       */
      enabled: boolean;
    };
    /**
     * RepositoriesConfig
     * @description Repositories configuration.
     */
    RepositoriesConfig: {
      /**
       * Lerobot Sources
       * @default []
       */
      lerobot_sources: components['schemas']['RepositorySource'][];
    };
    /**
     * RepositoryInfo
     * @description Repository information.
     */
    RepositoryInfo: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Url */
      url: string;
      /**
       * Is Default
       * @default false
       */
      is_default: boolean;
    };
    /**
     * RepositorySource
     * @description Repository source configuration.
     */
    RepositorySource: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Url */
      url: string;
      /**
       * Is Default
       * @default false
       */
      is_default: boolean;
    };
    /**
     * RepositoryStatus
     * @description Repository download status.
     */
    RepositoryStatus: {
      /** Repo Id */
      repo_id: string;
      /** Is Downloaded */
      is_downloaded: boolean;
      /** Last Updated */
      last_updated?: string | null;
      /** Cache Path */
      cache_path?: string | null;
    };
    /**
     * ServerConfig
     * @description Server configuration.
     */
    ServerConfig: {
      /**
       * Port
       * @default 8000
       */
      port: number;
      /**
       * Host
       * @default 127.0.0.1
       */
      host: string;
      /**
       * Auto Open Browser
       * @default true
       */
      auto_open_browser: boolean;
    };
    /**
     * StartInstallationResponse
     * @description Response for starting installation.
     */
    StartInstallationResponse: {
      /** Session Id */
      session_id: string;
      plan: components['schemas']['EnvironmentInstallationPlan'];
      /** Env Name */
      env_name: string;
    };
    /**
     * ToolSource
     * @description Tool source configuration.
     */
    ToolSource: {
      /**
       * Type
       * @default bundled
       * @enum {string}
       */
      type: 'bundled' | 'custom';
      /**
       * Custom Path
       * @default
       */
      custom_path: string;
    };
    /**
     * ToolsConfig
     * @description Tools configuration.
     */
    ToolsConfig: {
      git?: components['schemas']['ToolSource'];
    };
    /**
     * UIConfig
     * @description UI configuration.
     */
    UIConfig: {
      /**
       * Theme
       * @default system
       * @enum {string}
       */
      theme: 'system' | 'light' | 'dark';
      /**
       * Preferred Language
       * @default en
       * @enum {string}
       */
      preferred_language: 'en' | 'zh';
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VersionCompatibilityEntry
     * @description Compatibility entry for API response.
     */
    VersionCompatibilityEntry: {
      /** Torch */
      torch: string;
      /**
       * Cuda
       * @default []
       */
      cuda: string[];
      /**
       * Rocm
       * @default []
       */
      rocm: string[];
      /**
       * Cpu
       * @default false
       */
      cpu: boolean;
      /** Torchvision */
      torchvision?: string | null;
      /** Torchaudio */
      torchaudio?: string | null;
      /**
       * Is Recommended
       * @default false
       */
      is_recommended: boolean;
    };
    /**
     * VersionInfo
     * @description Version information.
     */
    VersionInfo: {
      /** Tag */
      tag: string;
      /** Is Stable */
      is_stable: boolean;
      /** Python Version */
      python_version?: string | null;
      /** Torch Version */
      torch_version?: string | null;
      /**
       * Compatibility Matrix
       * @default []
       */
      compatibility_matrix: components['schemas']['VersionCompatibilityEntry'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  hello_api_hello_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  hello_api_hello_head: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  get_current_config_api_app_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AppConfig-Output'];
        };
      };
    };
  };
  update_config_api_app_config_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AppConfig-Input'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AppConfig-Output'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reset_config_api_app_config_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AppConfig-Output'];
        };
      };
    };
  };
  get_has_environments_api_environments_has_environments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HasEnvironmentsResponse'];
        };
      };
    };
  };
  list_environments_api_environments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EnvironmentConfig'][];
        };
      };
    };
  };
  get_hardware_info_api_environments_hardware_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HardwareInfo'];
        };
      };
    };
  };
  get_available_extras_api_environments_extras_get: {
    parameters: {
      query: {
        /** @description Repository ID */
        repo_id: string;
        /** @description Git ref (branch/tag) */
        ref?: string;
        /** @description Language code */
        lang?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExtraInfo'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_installation_steps_api_environments_generate_steps_post: {
    parameters: {
      query?: {
        /** @description Language code */
        lang?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateStepsRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenerateStepsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_environment_api_environments_create_post: {
    parameters: {
      query?: {
        /** @description Language code */
        lang?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEnvironmentRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateEnvironmentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_environment_installation_status_api_environments__env_id__installation_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        env_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstallationStatusResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cancel_environment_installation_api_environments__env_id__installation_cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        env_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CancelInstallationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_environment_details_api_environments__env_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        env_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EnvironmentConfig'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_environment_api_environments__env_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        env_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteEnvironmentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_installation_api_environments__env_id__installation_start_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        env_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StartInstallationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  execute_installation_api_environments__env_id__installation_execute_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        env_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExecuteRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExecuteInstallationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_installation_status_api_environments__env_id__installation_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        env_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstallationStatusResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_repositories_api_repositories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RepositoryInfo'][];
        };
      };
    };
  };
  get_repository_versions_api_repositories__repo_id__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionInfo'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_repository_status_api_repositories__repo_id__status_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RepositoryStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stream_download_repository_api_repositories__repo_id__download_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        repo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  validate_git_path_api_tools_git_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: string;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_git_path_api_tools_git_which_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  get_bundled_git_status_api_tools_git_bundled_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
    };
  };
  download_bundled_git_api_tools_git_bundled_download_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
